#1st stage
FROM node:18-alpine as react-builder

WORKDIR /usr/src/app

COPY ./front-end/ .

RUN npm ci 

# Expose 8080

CMD ["npm","run","dev"]


# 2nd stage

# FROM httpd:2.4-alpine

# workdir /var/www/react

# COPY --from=react-builder /usr/src/app/dist /var/www