#stage 1
FROM node:18-alpine as react-builder

WORKDIR /usr/src/app

COPY ./front-end/ .

RUN npm ci 

Expose 8080

CMD ["npm","run","dev"]


#stage 2

# FROM httpd:2.4-alpine

# workdir /var/www/react

# COPY --from=react-builder /usr/src/app/dist /var/www/react

# EXPOSE 5173