#1st stage
FROM node:18-alpine as react-builder

WORKDIR /usr/src/app

COPY ./front-end/ .
ENV VITE_BACKEND_URL=http://localhost:9999

RUN mkdir cache && npm install -g npm@10.2.5 && npm config set cache ./cache --global && npm ci
RUN chown -R node /usr/src/app && chmod -R 777 /usr/src/app && chmod -R o+t /usr/src/app

Expose 8080

User node

CMD ["npm","run","dev"]


# 2nd stage

# FROM httpd:2.4-alpine

# workdir /var/www/react

# COPY --from=react-builder /usr/src/app/dist /var/www