#1st stage
FROM golang:1.21.3-bullseye as go-builder

WORKDIR /usr/src/app

COPY ./back-end/ .

RUN go mod download && go mod verify && go build -o main .


#2nd stage
FROM bitnami/minideb:stretch

WORKDIR /

COPY --from=go-builder /usr/src/app/main .
COPY --from=go-builder /usr/src/app/.env .

ARG port=9999

ENV port=${port}\
    mysql_url="root:password@tcp(localhost:3306)/clinic"\
    rabbitmq_url="amqp://guest:guest@localhost:5672/"\
    jwt_secret="ws-ws-ws-wsssssb"

# EXPOSE ${port}

CMD [ "./main" ]